export const PAYWALL_PLAN_LABEL_BY_LANGUAGE = {
  weekly: {
    ru: "Неделя",
    en: "Weekly",
    es: "Semanal",
    fr: "Hebdomadaire",
    de: "Wöchentlich",
    pt: "Semanal",
    it: "Settimanale",
    ar: "أسبوعي",
    zh: "周付",
    ko: "주간",
  },
  yearly: {
    ru: "Год",
    en: "Annual",
    es: "Anual",
    fr: "Annuel",
    de: "Jährlich",
    pt: "Anual",
    it: "Annuale",
    ar: "سنوي",
    zh: "年付",
    ko: "연간",
  },
  monthly: {
    ru: "Месяц",
    en: "Monthly",
    es: "Mensual",
    fr: "Mensuel",
    de: "Monatlich",
    pt: "Mensal",
    it: "Mensile",
    ar: "شهري",
    zh: "月付",
    ko: "월간",
  },
  lifetime: {
    ru: "Навсегда",
    en: "Lifetime",
    es: "De por vida",
    fr: "À vie",
    de: "Lebenslang",
    pt: "Vitalício",
    it: "A vita",
    ar: "مدى الحياة",
    zh: "终身",
    ko: "평생",
  },
  premium: {
    ru: "Premium",
    en: "Premium",
    es: "Premium",
    fr: "Premium",
    de: "Premium",
    pt: "Premium",
    it: "Premium",
    ar: "Premium",
    zh: "Premium",
    ko: "Premium",
  },
};

export const PAYWALL_SAVE_BADGE_TEMPLATE_BY_LANGUAGE = {
  ru: "Экономия {{percent}}%",
  en: "Save {{percent}}%",
  es: "Ahorra {{percent}}%",
  fr: "Économisez {{percent}}%",
  de: "Spare {{percent}}%",
  pt: "Poupa {{percent}}%",
  it: "Risparmia {{percent}}%",
  ar: "وفّر {{percent}}%",
  zh: "省 {{percent}}%",
  ko: "{{percent}}% 절약",
};

export const PAYWALL_TRIAL_BADGE_BY_LANGUAGE = {
  ru: "Пробный период",
  en: "Free trial",
  es: "Prueba gratis",
  fr: "Essai gratuit",
  de: "Kostenlos testen",
  pt: "Teste grátis",
  it: "Prova gratis",
  ar: "تجربة مجانية",
  zh: "免费试用",
  ko: "무료 체험",
};

export const PAYWALL_EQUIVALENT_SOURCE_IDS = [
  "coffee_to_go",
  "netflix_subscription",
  "croissant_break",
  "fancy_latte",
  "pizza",
  "late_night_takeout",
  "movie_premiere_combo",
  "comfort_utilities",
  "beauty_box",
  "grooming_upgrade_set",
  "studio_pass",
  "rent_upgrade",
];

export const PAYWALL_YEAR_SUFFIX_BY_LANGUAGE = {
  ru: "/год",
  en: "/yr",
  es: "/año",
  fr: "/an",
  de: "/Jahr",
  pt: "/ano",
  it: "/anno",
  ar: "/سنة",
  zh: "/年",
  ko: "/년",
};

export const PAYWALL_MONTH_SUFFIX_BY_LANGUAGE = {
  ru: "/мес",
  en: "/mo",
  es: "/mes",
  fr: "/mois",
  de: "/Monat",
  pt: "/mês",
  it: "/mese",
  ar: "/شهر",
  zh: "/月",
  ko: "/월",
};

export const PAYWALL_WEEK_SUFFIX_BY_LANGUAGE = {
  ru: "/нед",
  en: "/wk",
  es: "/sem",
  fr: "/sem",
  de: "/Woche",
  pt: "/semana",
  it: "/settimana",
  ar: "/أسبوع",
  zh: "/周",
  ko: "/주",
};

export const PAYWALL_BILLING_LABEL_BY_LANGUAGE = {
  weekly: {
    ru: "Списание каждую неделю",
    en: "Billed weekly",
    es: "Facturado semanalmente",
    fr: "Facturé chaque semaine",
    de: "Wöchentliche Abrechnung",
    pt: "Cobrado semanalmente",
    it: "Addebitato ogni settimana",
    ar: "يتم الفوترة أسبوعياً",
    zh: "按周计费",
    ko: "매주 청구",
  },
  yearly: {
    ru: "Списание раз в год",
    en: "Billed yearly",
    es: "Facturado anualmente",
    fr: "Facturé annuellement",
    de: "Jährliche Abrechnung",
    pt: "Cobrado anualmente",
    it: "Addebitato ogni anno",
    ar: "يتم الفوترة سنوياً",
    zh: "按年计费",
    ko: "매년 청구",
  },
  monthly: {
    ru: "Списание каждый месяц",
    en: "Billed monthly",
    es: "Facturado mensualmente",
    fr: "Facturé mensuellement",
    de: "Monatliche Abrechnung",
    pt: "Cobrado mensalmente",
    it: "Addebitato ogni mese",
    ar: "يتم الفوترة شهرياً",
    zh: "按月计费",
    ko: "매월 청구",
  },
  lifetime: {
    ru: "Разовый платеж",
    en: "One-time purchase",
    es: "Pago único",
    fr: "Achat unique",
    de: "Einmaliger Kauf",
    pt: "Pagamento único",
    it: "Pagamento unico",
    ar: "شراء لمرة واحدة",
    zh: "一次性购买",
    ko: "1회 결제",
  },
};

export const PAYWALL_EQUIVALENT_TEMPLATE_BY_LANGUAGE = {
  ru: {
    weekly: "≈ {{emoji}} {{count}} {{item}} в неделю",
    monthly: "≈ {{emoji}} {{count}} {{item}} в месяц",
    yearly: "≈ {{emoji}} {{count}} {{item}} в год",
    lifetime: "≈ {{emoji}} {{count}} {{item}} разово",
  },
  en: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / week",
    monthly: "≈ {{emoji}} {{count}} {{item}} / month",
    yearly: "≈ {{emoji}} {{count}} {{item}} / year",
    lifetime: "≈ {{emoji}} {{count}} {{item}} one-time",
  },
  es: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / semana",
    monthly: "≈ {{emoji}} {{count}} {{item}} / mes",
    yearly: "≈ {{emoji}} {{count}} {{item}} / año",
    lifetime: "≈ {{emoji}} {{count}} {{item}} una vez",
  },
  fr: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / semaine",
    monthly: "≈ {{emoji}} {{count}} {{item}} / mois",
    yearly: "≈ {{emoji}} {{count}} {{item}} / an",
    lifetime: "≈ {{emoji}} {{count}} {{item}} une fois",
  },
  de: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / Woche",
    monthly: "≈ {{emoji}} {{count}} {{item}} / Monat",
    yearly: "≈ {{emoji}} {{count}} {{item}} / Jahr",
    lifetime: "≈ {{emoji}} {{count}} {{item}} einmalig",
  },
  pt: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / semana",
    monthly: "≈ {{emoji}} {{count}} {{item}} / mês",
    yearly: "≈ {{emoji}} {{count}} {{item}} / ano",
    lifetime: "≈ {{emoji}} {{count}} {{item}} uma vez",
  },
  it: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / settimana",
    monthly: "≈ {{emoji}} {{count}} {{item}} / mese",
    yearly: "≈ {{emoji}} {{count}} {{item}} / anno",
    lifetime: "≈ {{emoji}} {{count}} {{item}} una volta",
  },
  ar: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / أسبوع",
    monthly: "≈ {{emoji}} {{count}} {{item}} / شهر",
    yearly: "≈ {{emoji}} {{count}} {{item}} / سنة",
    lifetime: "≈ {{emoji}} {{count}} {{item}} لمرة واحدة",
  },
  zh: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / 周",
    monthly: "≈ {{emoji}} {{count}} {{item}} / 月",
    yearly: "≈ {{emoji}} {{count}} {{item}} / 年",
    lifetime: "≈ {{emoji}} {{count}} {{item}} 一次性",
  },
  ko: {
    weekly: "≈ {{emoji}} {{count}} {{item}} / 주",
    monthly: "≈ {{emoji}} {{count}} {{item}} / 월",
    yearly: "≈ {{emoji}} {{count}} {{item}} / 년",
    lifetime: "≈ {{emoji}} {{count}} {{item}} 1회",
  },
};

export const PAYWALL_PERIOD_UNIT_TO_DAYS = {
  DAY: 1,
  WEEK: 7,
  MONTH: 30,
  YEAR: 365,
};

export const PAYWALL_TRIAL_CTA_DEFAULT_BY_LANGUAGE = {
  ru: "Начать бесплатный пробный период",
  en: "Start Free Trial",
  es: "Comenzar prueba gratis",
  fr: "Commencer l'essai gratuit",
  de: "Kostenlose Testversion starten",
  pt: "Iniciar teste grátis",
  it: "Inizia la prova gratis",
  ar: "ابدأ التجربة المجانية",
  zh: "开始免费试用",
  ko: "무료 체험 시작",
};

export const PAYWALL_POST_TRIAL_PREFIX_BY_LANGUAGE = {
  ru: "Бесплатный пробный период, затем",
  en: "Free trial then",
  es: "Prueba gratis, luego",
  fr: "Essaye gratuitement puis",
  de: "Kostenlos testen, danach",
  pt: "Teste grátis, depois",
  it: "Prova gratis, poi",
  ar: "جرّب مجاناً ثم",
  zh: "先免费试用，之后",
  ko: "무료 체험 후",
};

export const PAYWALL_NOW_PREFIX_BY_LANGUAGE = {
  ru: "Сейчас",
  en: "Now",
  es: "Ahora",
  fr: "Maintenant",
  de: "Jetzt",
  pt: "Agora",
  it: "Ora",
  ar: "الآن",
  zh: "现在",
  ko: "지금",
};

export const PAYWALL_MONTHLY_TRIAL_FALLBACK_DAYS = 7;
export const PAYWALL_YEARLY_TRIAL_FALLBACK_DAYS = 7;

export const PAYWALL_SAR_MARKERS_REGEX = /(﷼|sar|ر\.?\s*س\.?|ريال(?:ات)?)/gi;
export const PAYWALL_BIDI_MARKS_REGEX = /[\u200e\u200f\u061c]/g;
export const PAYWALL_DIGIT_FRAGMENT_REGEX = /[0-9\u0660-\u0669][0-9\u0660-\u0669\s.,]*/;

export const PAYWALL_ALERT_COPY = {
  missingAndroidApiKey: {
    ru: "Не найден EXPO_PUBLIC_RC_ANDROID_API_KEY. Добавьте переменную в Expo Environment Variables (preview/production), пересоберите приложение и повторите попытку.",
    en: "Missing EXPO_PUBLIC_RC_ANDROID_API_KEY. Add it to Expo Environment Variables (preview/production), rebuild the app, and try again.",
    es: "Falta EXPO_PUBLIC_RC_ANDROID_API_KEY. Añádela en Expo Environment Variables (preview/production), recompila la app e inténtalo de nuevo.",
    fr: "EXPO_PUBLIC_RC_ANDROID_API_KEY est manquante. Ajoutez-la dans Expo Environment Variables (preview/production), reconstruisez l'app puis réessayez.",
    pt: "Falta EXPO_PUBLIC_RC_ANDROID_API_KEY. Adiciona-a nas Expo Environment Variables (preview/production), recompila a app e tenta novamente.",
    it: "Manca EXPO_PUBLIC_RC_ANDROID_API_KEY. Aggiungila nelle Expo Environment Variables (preview/production), ricompila l'app e riprova.",
    ko: "EXPO_PUBLIC_RC_ANDROID_API_KEY가 없습니다. Expo Environment Variables(preview/production)에 추가하고 앱을 다시 빌드한 뒤 다시 시도하세요.",
  },
  packageUnavailable: {
    ru: "Этот вариант подписки сейчас недоступен. Попробуйте ещё раз чуть позже.",
    en: "This subscription option is unavailable right now. Please try again in a moment.",
    es: "Esta opción de suscripción no está disponible ahora mismo. Inténtalo de nuevo en breve.",
    fr: "Cette option d'abonnement est indisponible pour le moment. Réessayez dans un instant.",
    pt: "Esta opção de assinatura não está disponível agora. Tenta novamente daqui a pouco.",
    it: "Questa opzione di abbonamento non è disponibile ora. Riprova tra poco.",
    ko: "지금은 이 구독 옵션을 사용할 수 없습니다. 잠시 후 다시 시도하세요.",
  },
  offline: {
    ru: "Нет интернета. Подключитесь к сети и попробуйте снова.",
    en: "No internet connection. Connect to the internet and try again.",
    es: "No hay conexión a internet. Conéctate e inténtalo de nuevo.",
    fr: "Pas de connexion internet. Connectez-vous puis réessayez.",
    pt: "Sem ligação à internet. Liga-te à internet e tenta novamente.",
    it: "Nessuna connessione internet. Connettiti e riprova.",
    ko: "인터넷 연결이 없습니다. 연결한 뒤 다시 시도하세요.",
  },
  offeringsUnavailable: {
    ru: "Не удалось загрузить варианты подписки. Проверьте интернет и попробуйте снова.",
    en: "Could not load subscription options. Check your connection and try again.",
    es: "No se pudieron cargar las opciones de suscripción. Verifica tu conexión e inténtalo de nuevo.",
    fr: "Impossible de charger les options d'abonnement. Vérifiez votre connexion puis réessayez.",
    pt: "Não foi possível carregar as opções de assinatura. Verifica a ligação e tenta novamente.",
    it: "Impossibile caricare le opzioni di abbonamento. Controlla la connessione e riprova.",
    ko: "구독 옵션을 불러오지 못했습니다. 연결을 확인하고 다시 시도하세요.",
  },
  purchaseOffline: {
    ru: "Вы офлайн. Подключитесь к интернету, чтобы завершить покупку.",
    en: "You're offline. Connect to the internet to complete the purchase.",
    es: "Estás sin conexión. Conéctate a internet para completar la compra.",
    fr: "Vous êtes hors ligne. Connectez-vous à internet pour finaliser l'achat.",
    pt: "Estás offline. Liga-te à internet para concluir a compra.",
    it: "Sei offline. Connettiti a internet per completare l'acquisto.",
    ko: "오프라인 상태입니다. 구매를 완료하려면 인터넷에 연결하세요.",
  },
  restoreOffline: {
    ru: "Вы офлайн. Подключитесь к интернету, чтобы восстановить покупки.",
    en: "You're offline. Connect to the internet to restore purchases.",
    es: "Estás sin conexión. Conéctate a internet para restaurar las compras.",
    fr: "Vous êtes hors ligne. Connectez-vous à internet pour restaurer les achats.",
    pt: "Estás offline. Liga-te à internet para restaurar as compras.",
    it: "Sei offline. Connettiti a internet per ripristinare gli acquisti.",
    ko: "오프라인 상태입니다. 구매 복원을 하려면 인터넷에 연결하세요.",
  },
  purchaseFailed: {
    ru: "Не удалось завершить покупку. Попробуйте снова.",
    en: "Could not finish the purchase. Please try again.",
    es: "No se pudo completar la compra. Inténtalo de nuevo.",
    fr: "Impossible de finaliser l'achat. Réessayez.",
    pt: "Não foi possível concluir a compra. Tenta novamente.",
    it: "Impossibile completare l'acquisto. Riprova.",
    ko: "구매를 완료하지 못했습니다. 다시 시도하세요.",
  },
  restoreFailed: {
    ru: "Не удалось восстановить покупки.",
    en: "Could not restore purchases.",
    es: "No se pudieron restaurar las compras.",
    fr: "Impossible de restaurer les achats.",
    pt: "Não foi possível restaurar as compras.",
    it: "Impossibile ripristinare gli acquisti.",
    ko: "구매를 복원하지 못했습니다.",
  },
  noActiveSubscriptionIos: {
    ru: "Активная подписка не найдена. Проверьте Apple ID в Sandbox и повторите попытку.",
    en: "No active subscription was found. Verify your Sandbox Apple ID and try again.",
    es: "No se encontró una suscripción activa. Verifica tu Apple ID de Sandbox e inténtalo de nuevo.",
    fr: "Aucun abonnement actif n'a été trouvé. Vérifiez votre identifiant Apple Sandbox puis réessayez.",
    pt: "Não foi encontrada uma assinatura ativa. Verifica o teu Apple ID Sandbox e tenta novamente.",
    it: "Non è stato trovato un abbonamento attivo. Verifica l'Apple ID Sandbox e riprova.",
    ko: "활성 구독을 찾을 수 없습니다. Sandbox Apple ID를 확인하고 다시 시도하세요.",
  },
  noActiveSubscriptionAndroid: {
    ru: "Активная подписка не найдена. Проверьте Google Play тестовый аккаунт и повторите попытку.",
    en: "No active subscription was found. Verify your Google Play test account and try again.",
    es: "No se encontró una suscripción activa. Verifica tu cuenta de pruebas de Google Play e inténtalo de nuevo.",
    fr: "Aucun abonnement actif n'a été trouvé. Vérifiez votre compte test Google Play puis réessayez.",
    pt: "Não foi encontrada uma assinatura ativa. Verifica a tua conta de teste do Google Play e tenta novamente.",
    it: "Non è stato trovato un abbonamento attivo. Verifica l'account di test Google Play e riprova.",
    ko: "활성 구독을 찾을 수 없습니다. Google Play 테스트 계정을 확인하고 다시 시도하세요.",
  },
};
