export const DEFAULT_TEMPTATIONS = [
  {
    id: "coffee_to_go",
    emoji: "☕️",
    image:
      "https://images.unsplash.com/photo-1517705008128-361805f42e86?auto=format&fit=crop&w=600&q=80",
    color: "#FFF3E0",
    categories: ["food"],
    basePriceUSD: 5,
    priceUSD: 5,
    title: {
      ru: "Кофе навынос",
      en: "Coffee to-go",
      es: "Café para llevar",
      fr: "Café à emporter",
    },
    description: {
      ru: "Самая мелкая трата, которая, если её не заметить, съедает бюджет каждый день.",
      en: "Tiny daily swipe that quietly eats the budget if you don’t watch it.",
      es: "Ese pequeño pago diario que devora el presupuesto si no lo vigilas.",
      fr: "Ce petit achat quotidien finit par grignoter ton budget si tu ne le surveilles pas.",
    },
  },
  {
    id: "netflix_subscription",
    emoji: "📺",
    image:
      "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?auto=format&fit=crop&w=600&q=80",
    color: "#F2F2F2",
    categories: ["subscriptions"],
    basePriceUSD: 7,
    priceUSD: 7,
    title: {
      ru: "Подписка на Нетфликс",
      en: "Netflix subscription",
      es: "Suscripción a Netflix",
      fr: "Abonnement Netflix",
    },
    description: {
      ru: "Маленькая ежемесячная подписка, которая незаметно тянет бюджет вниз.",
      en: "A small monthly subscription that quietly drains the budget.",
      es: "Una suscripción mensual pequeña que va drenando el presupuesto.",
      fr: "Un petit abonnement mensuel qui grignote le budget sans bruit.",
    },
  },
  {
    id: "croissant_break",
    emoji: "🥐",
    image:
      "https://images.unsplash.com/photo-1464306076886-da185f6a9d12?auto=format&fit=crop&w=600&q=80",
    color: "#FFFBEA",
    categories: ["food"],
    basePriceUSD: 8,
    priceUSD: 8,
    title: {
      ru: "Утренний круассан",
      en: "Morning croissant",
      es: "Croissant mañanero",
      fr: "Croissant du matin",
    },
    description: {
      ru: "Маленькое удовольствие, которое запускает большой прогресс, если его отложить.",
      en: "A tiny treat that becomes a big level boost once you skip it.",
      es: "Un pequeño antojo que impulsa el progreso cuando lo pospones.",
      fr: "Ce petit plaisir devient un vrai boost de progression quand tu le remets à plus tard.",
    },
  },
  {
    id: "fancy_latte",
    emoji: "🥤",
    image:
      "https://images.unsplash.com/photo-1509043759401-136742328bb3?auto=format&fit=crop&w=600&q=80",
    color: "#E8F5E9",
    categories: ["food"],
    basePriceUSD: 12,
    priceUSD: 12,
    title: {
      ru: "Матча-латте",
      en: "Matcha latte",
      es: "Matcha latte",
      fr: "Matcha latte",
    },
    description: {
      ru: "Стеклянный стакан + топинг = почти абонемент в спортзал за месяц.",
      en: "Glass cup + topping = nearly a gym pass per month if you bank it.",
      es: "Vaso chic + topping = casi una mensualidad de gimnasio si lo ahorras.",
      fr: "Verre stylé + topping = presque un abonnement de gym par mois si tu l'économises.",
    },
  },
  {
    id: "phone",
    emoji: "📱",
    image:
      "https://images.unsplash.com/photo-1501426026826-31c667bdf23d?auto=format&fit=crop&w=600&q=80",
    color: "#F6DFFF",
    categories: ["clothing"],
    basePriceUSD: 1199,
    priceUSD: 1199,
    title: {
      ru: "Новый смартфон",
      en: "New smartphone",
      es: "Smartphone nuevo",
      fr: "Nouveau smartphone",
    },
    description: {
      ru: "Свежий гаджет с двойной камерой, который так легко оправдать. Проверим, стоит ли он эмоций?",
      en: "Shiny dual-camera flagship tempting every scroll. Is the hype worth your savings?",
      es: "Nuevo flagship con doble cámara que tienta en cada scroll. ¿Vale tus ahorros?",
      fr: "Ce flagship brillant à double caméra tente à chaque scroll. L'engouement mérite-t-il tes économies ?",
    },
  },
  {
    id: "sneakers",
    emoji: "👟",
    image:
      "https://images.unsplash.com/photo-1528701800489-20be3cbe2c05?auto=format&fit=crop&w=600&q=80",
    color: "#E3F6E8",
    categories: ["clothing"],
    basePriceUSD: 260,
    priceUSD: 260,
    title: {
      ru: "Лимитированные кроссы",
      en: "Limited sneakers",
      es: "Tenis limitados",
      fr: "Sneakers en édition limitée",
    },
    description: {
      ru: "Редкий дроп с очередью из желающих. Иногда вместо очереди лучше пополнить копилку.",
      en: "Rare drop everyone chases. Maybe the real flex is topping up your stash.",
      es: "Drop limitado que todos persiguen. El verdadero lujo puede ser engordar la alcancía.",
      fr: "Un drop rare que tout le monde pourchasse. Et si le vrai flex était de gonfler ta cagnotte ?",
    },
  },
  {
    id: "watch",
    emoji: "⌚️",
    image:
      "https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=600&q=80",
    color: "#FFE5F1",
    categories: ["things"],
    basePriceUSD: 799,
    priceUSD: 799,
    title: {
      ru: "Премиальные часы",
      en: "Premium watch",
      es: "Reloj premium",
      fr: "Montre premium",
    },
    description: {
      ru: "Отслеживает пульс и расходы, если враг не носит их каждый день.",
      en: "Tracks your pulse and spending if you resist wearing it daily.",
      es: "Controla tu pulso (y tu gasto) si lo dejas en la vitrina un día más.",
      fr: "Suit ton pouls et tes dépenses… si tu résistes à la porter tous les jours.",
    },
  },
  {
    id: "console",
    emoji: "🎮",
    image:
      "https://images.unsplash.com/photo-1486401899868-0e435ed85128?auto=format&fit=crop&w=600&q=80",
    color: "#D9F7FF",
    categories: ["things"],
    audience: ["male"],
    basePriceUSD: 549,
    priceUSD: 549,
    title: {
      ru: "Игровая приставка",
      en: "Game console",
      es: "Consola de juegos",
      fr: "Console de jeu",
    },
    description: {
      ru: "Лучший способ вечерами спасать мир и бюджет. До тех пор, пока ты не нажал «купить».",
      en: "Saves worlds at night and your budget if you pause before checkout.",
      es: "Salva mundos por la noche y tu presupuesto si te detienes antes de pagar.",
      fr: "Sauve des mondes le soir et ton budget si tu fais une pause avant de payer.",
    },
  },
  {
    id: "pizza",
    emoji: "🍕",
    image:
      "https://images.unsplash.com/photo-1542281286-9e0a16bb7366?auto=format&fit=crop&w=600&q=80",
    color: "#FFF4D5",
    categories: ["food"],
    basePriceUSD: 25,
    priceUSD: 25,
    title: {
      ru: "Сет пицц и роллов",
      en: "Pizza & rolls night",
      es: "Noche de pizza y rolls",
      fr: "Nuit pizza & rolls",
    },
    description: {
      ru: "Пятничный ритуал, который легко превращается в тысячу рублей, улетевших в никуда.",
      en: "Friday ritual that quickly becomes a $40 habit. Maybe cook tonight?",
      es: "Ritual de viernes que se vuelve un hábito de $40. ¿Y si cocinas hoy?",
      fr: "Rituel du vendredi qui finit vite en habitude à 40 $. Et si tu cuisinais ce soir ?",
    },
  },
  {
    id: "late_night_takeout",
    emoji: "🍱",
    image:
      "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?auto=format&fit=crop&w=900&q=80",
    color: "#FFEFE9",
    categories: ["food"],
    basePriceUSD: 35,
    priceUSD: 35,
    title: {
      ru: "Дополнительный сет роллов",
      en: "Extra sushi add-on",
      es: "Extra de sushi nocturno",
      fr: "Supplément sushi de nuit",
    },
    description: {
      ru: "Кажется мелочью в доставке, но именно он делает чек заметно выше.",
      en: "Tiny add-on in the cart that silently pushes the total over the top.",
      es: "Ese extra pequeño en la app que dispara la cuenta final.",
      fr: "Ce petit extra dans le panier qui fait grimper la note sans prévenir.",
    },
  },
  {
    id: "movie_premiere_combo",
    emoji: "🎬",
    image:
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=900&q=80",
    color: "#F4F2FF",
    categories: ["fun"],
    basePriceUSD: 45,
    priceUSD: 45,
    title: {
      ru: "Кино + закуски",
      en: "Movie night combo",
      es: "Combo noche de cine",
      fr: "Combo soirée cinéma",
    },
    description: {
      ru: "Билеты, попкорн и лимонад, которые легко превратить в взнос в копилку.",
      en: "Tickets, popcorn and soda that could become a little boost to savings.",
      es: "Entradas, palomitas y refresco que podrían ir directo al ahorro.",
      fr: "Tickets, pop-corn et soda qui pourraient devenir un coup de pouce pour l'épargne.",
    },
  },
  {
    id: "cocktail_night",
    emoji: "🍸",
    image:
      "https://images.unsplash.com/photo-1514361892635-6b07e31e75f9?auto=format&fit=crop&w=900&q=80",
    color: "#FFF2E8",
    categories: ["vices"],
    basePriceUSD: 55,
    priceUSD: 55,
    title: {
      ru: "Коктейльная ночь",
      en: "Cocktail night",
      es: "Noche de cócteles",
      fr: "Soirée cocktails",
    },
    description: {
      ru: "Пара бокалов и лёгкий автопилот по карте. Попробуй паузу и забери победу.",
      en: "A couple of rounds on autopilot. Pause once and claim the win.",
      es: "Un par de rondas en piloto automático. Pausa y gana.",
      fr: "Deux tournées en pilote automatique. Fais une pause et gagne.",
    },
  },
  {
    id: "comfort_utilities",
    emoji: "💡",
    image:
      "https://images.unsplash.com/photo-1509395176047-4a66953fd231?auto=format&fit=crop&w=900&q=80",
    color: "#F5F9FF",
    categories: ["utilities"],
    basePriceUSD: 65,
    priceUSD: 65,
    title: {
      ru: "Комфортный счёт за коммуналку",
      en: "Comfort-first utilities",
      es: "Servicios sin límites",
      fr: "Confort sans limites",
    },
    description: {
      ru: "Тёплый пол и кондиционер на максимум. Счёт вырастает незаметно.",
      en: "Heat and AC at full blast make the bill climb quietly.",
      es: "Calefacción y aire a tope: la cuenta sube sin aviso.",
      fr: "Chauffage et clim à fond : la facture grimpe sans prévenir.",
    },
  },
  {
    id: "pet_spa_day",
    emoji: "🐶",
    image:
      "https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=900&q=80",
    color: "#FFF7E8",
    categories: ["pets"],
    basePriceUSD: 95,
    priceUSD: 95,
    title: {
      ru: "SPA-день для питомца",
      en: "Pet spa day",
      es: "Spa para tu mascota",
      fr: "Spa pour ton animal",
    },
    description: {
      ru: "Груминг, игрушки и лакомства: мило, но можно отложить ради цели.",
      en: "Grooming, toys and treats are cute, but goals can wait less.",
      es: "Peluquería, juguetes y premios: lindo, pero tus metas importan.",
      fr: "Toilettage, jouets, friandises : mignon, mais tes objectifs comptent.",
    },
  },
  {
    id: "beauty_box",
    emoji: "💄",
    image:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    color: "#FFE9F2",
    categories: ["beauty"],
    audience: ["female"],
    basePriceUSD: 65,
    priceUSD: 65,
    title: {
      ru: "Beauty-бокс месяца",
      en: "Monthly beauty box",
      es: "Caja beauty mensual",
      fr: "Box beauté du mois",
    },
    description: {
      ru: "Коробочка сюрпризов, которая каждый месяц перетягивает бюджет.",
      en: "A curated surprise box that steals a chunk of the monthly plan.",
      es: "Caja sorpresa curada que se lleva parte del plan mensual.",
      fr: "Une box surprise bien pensée qui mord chaque mois dans ton budget.",
    },
  },
  {
    id: "grooming_upgrade_set",
    emoji: "🪒",
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80",
    color: "#E9F8FF",
    categories: ["beauty"],
    audience: ["male"],
    basePriceUSD: 70,
    priceUSD: 70,
    title: {
      ru: "Премиум-набор для ухода",
      en: "Premium grooming bundle",
      es: "Set premium de cuidado",
      fr: "Coffret grooming premium",
    },
    description: {
      ru: "Бритва, масла и триммер, которые легко заменить прогрессом по целям.",
      en: "Razor, oils and trimmer that could become goal progress instead.",
      es: "Rasuradora, aceites y trimmer que podrían ser avance hacia tu meta.",
      fr: "Rasoir, huiles et tondeuse qui pourraient devenir des points de progrès.",
    },
  },
  {
    id: "smart_band_upgrade",
    emoji: "📿",
    image:
      "https://images.unsplash.com/photo-1517148815974-413097f4a0c0?auto=format&fit=crop&w=900&q=80",
    color: "#E9F5FF",
    categories: ["health"],
    basePriceUSD: 90,
    priceUSD: 90,
    title: {
      ru: "Новый фитнес-браслет",
      en: "Fresh fitness band",
      es: "Nueva smartband",
      fr: "Nouveau bracelet fitness",
    },
    description: {
      ru: "Экран побольше, датчиков побольше и еще один повод отложить upgrade.",
      en: "Bigger screen, more sensors and one more reason to pause the upgrade.",
      es: "Pantalla más grande y sensores extra: otro motivo para frenar el upgrade.",
      fr: "Écran plus grand, capteurs en plus et une raison de plus d'attendre avant l'upgrade.",
    },
  },
  {
    id: "weekend_brunch",
    emoji: "🥞",
    image:
      "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=900&q=80",
    color: "#FFF7EA",
    categories: ["food"],
    basePriceUSD: 120,
    priceUSD: 120,
    title: {
      ru: "Бранч выходного дня",
      en: "Weekend brunch ritual",
      es: "Ritual de brunch",
      fr: "Rituel brunch du week-end",
    },
    description: {
      ru: "Слои панкейков и мимозы легко превращаются в прогресс по целям.",
      en: "Stacks of pancakes and mimosas that could have been goal progress.",
      es: "Capas de pancakes y mimosas que podrían ser progreso de metas.",
      fr: "Des piles de pancakes et des mimosas qui pourraient devenir du progrès vers tes objectifs.",
    },
  },
  {
    id: "studio_pass",
    emoji: "🧘",
    image:
      "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80",
    color: "#E9FFF2",
    categories: ["health"],
    basePriceUSD: 180,
    priceUSD: 180,
    title: {
      ru: "Пакет из 10 тренировок",
      en: "10-class studio pass",
      es: "Pase de 10 clases",
      fr: "Pass studio 10 séances",
    },
    description: {
      ru: "Красивая подписка, которая окупится, если копилка останется приоритетом.",
      en: "A shiny class pack that pays off only if the jar stays priority.",
      es: "Un paquete brillante que solo rinde si el ahorro sigue siendo prioridad.",
      fr: "Un pack de cours canon qui ne vaut le coup que si la cagnotte reste prioritaire.",
    },
  },
  {
    id: "insurance_renewal",
    emoji: "🧾",
    image:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=900&q=80",
    color: "#F6F2FF",
    categories: ["mandatory"],
    basePriceUSD: 220,
    priceUSD: 220,
    title: {
      ru: "Продление страховки",
      en: "Insurance renewal",
      es: "Renovación de seguro",
      fr: "Renouvellement d'assurance",
    },
    description: {
      ru: "Обязательный платёж, который легко сделать легче: проверь опции.",
      en: "A required payment that can feel lighter when you check the options.",
      es: "Pago obligatorio que puede aliviarse si revisas opciones.",
      fr: "Paiement obligatoire qui peut être allégé en comparant les options.",
    },
  },
  {
    id: "online_course_bundle",
    emoji: "🎓",
    image:
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=900&q=80",
    color: "#F0F7FF",
    categories: ["education"],
    basePriceUSD: 240,
    priceUSD: 240,
    title: {
      ru: "Пакет онлайн-курсов",
      en: "Online course bundle",
      es: "Paquete de cursos online",
      fr: "Pack de cours en ligne",
    },
    description: {
      ru: "Классный апгрейд навыков, но можно подождать и накопить спокойно.",
      en: "A skills upgrade that’s great, but can wait while you save.",
      es: "Un impulso de habilidades genial, pero puede esperar mientras ahorras.",
      fr: "Une amélioration des compétences sympa, mais ça peut attendre.",
    },
  },
  {
    id: "streetwear_capsule",
    emoji: "🧥",
    image:
      "https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=900&q=80",
    color: "#EAF2FF",
    categories: ["clothing"],
    basePriceUSD: 220,
    priceUSD: 220,
    title: {
      ru: "Стритвир-капсула",
      en: "Streetwear capsule",
      es: "Cápsula streetwear",
      fr: "Capsule streetwear",
    },
    description: {
      ru: "Худи, кепка и аксессуары, которые легко превратить в вклад в большую мечту.",
      en: "Hoodie, cap and trinkets that could accelerate the bigger dream.",
      es: "Hoodie, gorra y accesorios que podrían empujar tu gran sueño.",
      fr: "Hoodie, casquette et accessoires qui pourraient plutôt accélérer ton grand rêve.",
    },
  },
  {
    id: "vacation",
    emoji: "🏝️",
    image:
      "https://images.unsplash.com/photo-1496417263034-38ec4f0b665a?auto=format&fit=crop&w=600&q=80",
    color: "#E0F7FA",
    categories: ["fun"],
    basePriceUSD: 1800,
    priceUSD: 1800,
    title: {
      ru: "Экспресс-путешествие",
      en: "Flash vacation",
      es: "Escapada exprés",
      fr: "Escapade éclair",
    },
    description: {
      ru: "Ловим билеты на море до зарплаты. Или копим заранее и летим без стресса.",
      en: "Spontaneous seaside flights before payday or a mindful trip later.",
      es: "Vuelos a la playa antes de cobrar o un viaje con calma si lo planificas.",
      fr: "Vols improvisés avant la paie ou voyage paisible si tu l'anticipes.",
    },
  },
  {
    id: "coffee",
    emoji: "☕️",
    image:
      "https://images.unsplash.com/photo-1481391032119-d89fee407e44?auto=format&fit=crop&w=600&q=80",
    color: "#FAF0E6",
    categories: ["home"],
    basePriceUSD: 320,
    priceUSD: 320,
    title: {
      ru: "Домашняя кофемашина",
      en: "Home coffee setup",
      es: "Cafetera en casa",
      fr: "Machine à café maison",
    },
    description: {
      ru: "Бариста на кухне и минус десяток походов в кофейню каждую неделю.",
      en: "Barista on the countertop and fewer pricey coffee runs.",
      es: "Un barista en tu cocina y menos visitas costosas a la cafetería.",
      fr: "Un barista sur le plan de travail et moins d'allers-retours coûteux au café.",
    },
  },
  {
    id: "bag",
    emoji: "👜",
    image:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=600&q=80",
    color: "#F8F1FF",
    categories: ["clothing"],
    audience: ["female"],
    basePriceUSD: 950,
    priceUSD: 950,
    title: {
      ru: "Дизайнерская сумка",
      en: "Designer bag",
      es: "Bolso de diseñador",
      fr: "Sac de créateur",
    },
    description: {
      ru: "Вещь мечты, которая либо вдохновляет, либо возвращает к списку финансовых целей.",
      en: "Statement piece that either inspires or reminds you of bigger goals.",
      es: "Pieza soñada que inspira o te recuerda metas más grandes.",
      fr: "Pièce signature qui inspire ou te rappelle des objectifs plus grands.",
    },
  },
  {
    id: "city_escape",
    emoji: "🌆",
    image:
      "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?auto=format&fit=crop&w=600&q=80",
    color: "#E3E5FF",
    categories: ["fun"],
    basePriceUSD: 1200,
    priceUSD: 1200,
    title: {
      ru: "Уикенд в европейском городе",
      en: "Weekend city escape",
      es: "Escapada urbana",
      fr: "Escapade urbaine",
    },
    description: {
      ru: "Два дня архитектуры и кофе или месячный запас сбережений.",
      en: "Two days of architecture and espresso or a month of savings momentum.",
      es: "Dos días de arquitectura y espresso o un mes de impulso de ahorro.",
      fr: "Deux jours d'architecture et d'espresso ou un mois d'élan d'épargne.",
    },
  },
  {
    id: "road_trip",
    emoji: "🚐",
    image:
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=80",
    color: "#E0FFF6",
    categories: ["fun"],
    basePriceUSD: 3200,
    priceUSD: 3200,
    title: {
      ru: "Путешествие на машине мечты",
      en: "Dream road trip",
      es: "Road trip soñado",
      fr: "Road trip de rêve",
    },
    description: {
      ru: "Бензин, дом на колёсах и свобода. Всё это может подождать до полного прогресса.",
      en: "Fuel, van life and freedom are all waiting once the progress bar hits max.",
      es: "Gasolina, van y libertad te esperan cuando la barra de progreso llegue al tope.",
      fr: "Carburant, vanlife et liberté attendent une fois la barre de progression au max.",
    },
  },
  {
    id: "dream_car",
    emoji: "🚗",
    image:
      "https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=80",
    color: "#FFE0E3",
    categories: ["car"],
    basePriceUSD: 28000,
    priceUSD: 28000,
    title: {
      ru: "Автомобиль мечты",
      en: "Dream car",
      es: "Auto de ensueño",
      fr: "Voiture de rêve",
    },
    description: {
      ru: "Каждый «сэкономить» переводит топливо из чата хотелок в гараж будущего.",
      en: "Every “save it” reroutes fuel from impulse chats into the future garage.",
      es: "Cada “ahórralo” desvía combustible de los impulsos al garaje futuro.",
      fr: "Chaque « j'économise » détourne du carburant des chats d'impulsion vers ton garage futur.",
    },
  },
  {
    id: "dream_home",
    emoji: "🏡",
    image:
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80",
    color: "#FFF1E6",
    categories: ["home"],
    basePriceUSD: 90000,
    priceUSD: 90000,
    title: {
      ru: "Взнос за квартиру",
      en: "Home down payment",
      es: "Enganche para casa",
      fr: "Apport pour la maison",
    },
    description: {
      ru: "Пусть отказ от доставок превращается в кирпичи твоего будущего адреса.",
      en: "Every skipped delivery becomes a brick in your future address.",
      es: "Cada entrega que saltas se convierte en un ladrillo de tu futuro hogar.",
      fr: "Chaque livraison évitée devient une brique de ton adresse future.",
    },
  },
  {
    id: "private_jet",
    emoji: "🛩️",
    image:
      "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
    color: "#EDF7FF",
    categories: ["transport"],
    basePriceUSD: 250000,
    priceUSD: 250000,
    title: {
      ru: "Частный самолёт (мечта)",
      en: "Private jet (why not)",
      es: "Jet privado (por qué no)",
      fr: "Jet privé (pourquoi pas)",
    },
    description: {
      ru: "Чистая геймификация: уровень «самолёт» показывает безлимитную дисциплину.",
      en: "Pure gamification: the jet tier proves your discipline is first class.",
      es: "Gamificación pura: nivel jet demuestra disciplina de primera clase.",
      fr: "Pure gamification : ce palier “jet” prouve une discipline première classe.",
    },
  },
  {
    id: "rent_upgrade",
    emoji: "🏠",
    image:
      "https://images.unsplash.com/photo-1527030280862-64139fba04ca?auto=format&fit=crop&w=900&q=80",
    color: "#EFFFF4",
    categories: ["rent"],
    basePriceUSD: 450,
    priceUSD: 450,
    title: {
      ru: "Апгрейд аренды",
      en: "Rent upgrade",
      es: "Mejora de alquiler",
      fr: "Upgrade de loyer",
    },
    description: {
      ru: "Больше пространства и света звучит классно, но можно подготовиться без стресса.",
      en: "More space and light sound great, but you can prep for it without stress.",
      es: "Más espacio y luz suenan bien, pero puedes prepararlo sin estrés.",
      fr: "Plus d'espace et de lumière, c'est tentant, mais tu peux te préparer sereinement.",
    },
  },
];
