export const THEMES = {
  light: {
    appearance: "light",
    background: "#F5F6F8",
    card: "#FFFFFF",
    text: "#202129",
    muted: "#626774",
    border: "#D8DCE3",
    primary: "#24262D",
    onPrimary: "#F8F9FB",
    surface: "#FFFFFF",
    surfaceMuted: "#ECEEF2",
    surfaceElevated: "#FFFFFF",
    separator: "#DDE0E6",
    disabled: "#8B909C",
    success: "#247451",
    warning: "#8B5A16",
    error: "#A73D37",
    info: "#356A9A",
    primarySurface: "#E8EAEF",
    primarySurfaceStrong: "#DDE0E6",
    primaryBorder: "#C9CDD5",
    overlay: "#111318",
    shadow: "#191B22",
  },
  dark: {
    appearance: "dark",
    background: "#05070D",
    card: "#141923",
    text: "#EEF1F6",
    muted: "#9EA8BA",
    border: "#2B3342",
    primary: "#D7A84F",
    onPrimary: "#211A0B",
    surface: "#141923",
    surfaceMuted: "#1B2230",
    surfaceElevated: "#202735",
    separator: "#343D4D",
    disabled: "#717A8C",
    success: "#66B991",
    warning: "#D8AC5F",
    error: "#E2938B",
    info: "#79A9D4",
    primarySurface: "#2A2519",
    primarySurfaceStrong: "#39301D",
    primaryBorder: "#62502C",
    overlay: "#020307",
    shadow: "#020308",
  },
  pro: {
    appearance: "light",
    background: "#ECEFFD",
    card: "#FAFAFF",
    text: "#171C46",
    muted: "#565F86",
    border: "#B9C2EB",
    primary: "#3E4FD7",
    onPrimary: "#FFFFFF",
    surface: "#FAFAFF",
    surfaceMuted: "#DEE4FA",
    surfaceElevated: "#F5F6FF",
    separator: "#C7CFEF",
    disabled: "#737C9D",
    success: "#247451",
    warning: "#825A1E",
    error: "#A73D37",
    info: "#356A9A",
    primarySurface: "#D7DEFF",
    primarySurfaceStrong: "#BBC7FF",
    primaryBorder: "#8C9CE8",
    overlay: "#0E1336",
    shadow: "#243585",
  },
};

export const DEFAULT_THEME = "light";
export const PRO_THEME_ID = "pro";
export const THEME_IDS = ["light", "dark", PRO_THEME_ID];

export const PRO_THEME_ACCENT_OPTIONS = [
  {
    id: "indigo",
    accent: "#3E4FD7",
    onAccent: "#FFFFFF",
    palette: {
      background: "#ECEFFD",
      card: "#FAFAFF",
      text: "#171C46",
      muted: "#565F86",
      border: "#B9C2EB",
      surface: "#FAFAFF",
      surfaceMuted: "#DEE4FA",
      surfaceElevated: "#F5F6FF",
      separator: "#C7CFEF",
      disabled: "#737C9D",
      primarySurface: "#D7DEFF",
      primarySurfaceStrong: "#BBC7FF",
      primaryBorder: "#8C9CE8",
      overlay: "#0E1336",
      shadow: "#243585",
    },
    label: {
      ru: "Индиго",
      en: "Indigo",
      es: "Índigo",
      fr: "Indigo",
      de: "Indigo",
      pt: "Índigo",
      it: "Indaco",
      ar: "نيلي",
      zh: "靛蓝",
      ko: "인디고",
    },
    emoji: "🔵",
  },
  {
    id: "emerald",
    accent: "#15755E",
    onAccent: "#FFFFFF",
    palette: {
      background: "#E7F4EF",
      card: "#F8FCFA",
      text: "#12372E",
      muted: "#49685F",
      border: "#AACFC2",
      surface: "#F8FCFA",
      surfaceMuted: "#D7EAE3",
      surfaceElevated: "#F1F9F6",
      separator: "#B9D9CE",
      disabled: "#6E8B82",
      primarySurface: "#CDE6DC",
      primarySurfaceStrong: "#A8D4C4",
      primaryBorder: "#73B29C",
      overlay: "#082D24",
      shadow: "#0D5947",
    },
    label: {
      ru: "Изумруд",
      en: "Emerald",
      es: "Esmeralda",
      fr: "Émeraude",
      de: "Smaragd",
      pt: "Esmeralda",
      it: "Smeraldo",
      ar: "زمردي",
      zh: "祖母绿",
      ko: "에메랄드",
    },
    emoji: "💚",
  },
  {
    id: "sunset",
    accent: "#B84D3E",
    onAccent: "#FFFFFF",
    palette: {
      background: "#FCEBE7",
      card: "#FFFBFA",
      text: "#43201C",
      muted: "#755B55",
      border: "#E2BEB5",
      surface: "#FFFBFA",
      surfaceMuted: "#F6DDD6",
      surfaceElevated: "#FFF7F4",
      separator: "#E9CEC7",
      disabled: "#967B75",
      primarySurface: "#F8D4CB",
      primarySurfaceStrong: "#EFADA0",
      primaryBorder: "#D98373",
      overlay: "#35120C",
      shadow: "#7D2F25",
    },
    label: {
      ru: "Сансет",
      en: "Sunset",
      es: "Atardecer",
      fr: "Coucher",
      de: "Sonnenuntergang",
      pt: "Pôr do sol",
      it: "Tramonto",
      ar: "غروب",
      zh: "日落",
      ko: "선셋",
    },
    emoji: "🌇",
  },
  {
    id: "gold",
    accent: "#8A5D0A",
    onAccent: "#FFFFFF",
    palette: {
      background: "#FAF2DA",
      card: "#FFFCF4",
      text: "#3F2E0F",
      muted: "#705F3B",
      border: "#DCCB9E",
      surface: "#FFFCF4",
      surfaceMuted: "#F2E5BE",
      surfaceElevated: "#FFF8E8",
      separator: "#E4D5AF",
      disabled: "#8D7E5D",
      primarySurface: "#F1DEAA",
      primarySurfaceStrong: "#E4C36F",
      primaryBorder: "#C7A34C",
      overlay: "#302006",
      shadow: "#6C4708",
    },
    label: { ru: "Золото", en: "Gold", es: "Oro", fr: "Or", de: "Gold", pt: "Ouro", it: "Oro", ar: "ذهبي", zh: "金色", ko: "골드" },
    emoji: "✨",
  },
  {
    id: "violet",
    accent: "#7152C8",
    onAccent: "#FFFFFF",
    palette: {
      background: "#F2ECFB",
      card: "#FCFAFF",
      text: "#2A1B48",
      muted: "#665B7A",
      border: "#CDBBE8",
      surface: "#FCFAFF",
      surfaceMuted: "#E8DCF5",
      surfaceElevated: "#F8F4FC",
      separator: "#D9CDEB",
      disabled: "#887D99",
      primarySurface: "#E2D4F5",
      primarySurfaceStrong: "#CBB2EB",
      primaryBorder: "#A98AD8",
      overlay: "#211137",
      shadow: "#503083",
    },
    label: {
      ru: "Фиолет",
      en: "Violet",
      es: "Violeta",
      fr: "Violet",
      de: "Violett",
      pt: "Violeta",
      it: "Viola",
      ar: "بنفسجي",
      zh: "紫色",
      ko: "바이올렛",
    },
    emoji: "🍇",
  },
  {
    id: "aqua",
    accent: "#087E9B",
    onAccent: "#FFFFFF",
    palette: {
      background: "#E5F5F7",
      card: "#F8FCFD",
      text: "#10373F",
      muted: "#4B6C72",
      border: "#ADD4DA",
      surface: "#F8FCFD",
      surfaceMuted: "#D6EAED",
      surfaceElevated: "#F1F9FA",
      separator: "#BDDDE1",
      disabled: "#6B8B90",
      primarySurface: "#CBE8EC",
      primarySurfaceStrong: "#9FD6DD",
      primaryBorder: "#63B8C5",
      overlay: "#072D34",
      shadow: "#0B6171",
    },
    label: { ru: "Аква", en: "Aqua", es: "Aqua", fr: "Aqua", de: "Aqua", pt: "Aqua", it: "Acqua", ar: "أكوا", zh: "水蓝", ko: "아쿠아" },
    emoji: "🌊",
  },
];

export const DEFAULT_PRO_THEME_ACCENT_ID = "indigo";


export const PRO_THEME_ACCENT_COPY = {
  ru: {
    title: "Акцент PRO-темы",
    subtitle: "Выбери цвет, который будет использоваться для кнопок и акцентов интерфейса.",
    selected: "Выбрано",
  },
  en: {
    title: "PRO theme accent",
    subtitle: "Pick the color used for buttons and highlighted UI accents.",
    selected: "Selected",
  },
  es: {
    title: "Acento del tema PRO",
    subtitle: "Elige el color para botones y acentos principales de la interfaz.",
    selected: "Seleccionado",
  },
  fr: {
    title: "Accent du thème PRO",
    subtitle: "Choisis la couleur utilisée pour les boutons et accents d'interface.",
    selected: "Sélectionné",
  },
  de: {
    title: "PRO-Theme-Akzent",
    subtitle: "Wähle die Farbe für Buttons und hervorgehobene UI-Akzente.",
    selected: "Ausgewählt",
  },
  pt: {
    title: "Acento do tema PRO",
    subtitle: "Escolhe a cor usada nos botões e nos destaques da interface.",
    selected: "Selecionado",
  },
  it: {
    title: "Accento tema PRO",
    subtitle: "Scegli il colore usato per pulsanti e accenti evidenziati dell'interfaccia.",
    selected: "Selezionato",
  },
  ar: {
    title: "تمييز سمة PRO",
    subtitle: "اختر اللون المستخدم للأزرار وإبرازات الواجهة.",
    selected: "محدد",
  },
  zh: {
    title: "PRO 主题强调色",
    subtitle: "选择用于按钮和界面高亮的颜色。",
    selected: "已选择",
  },
  ko: {
    title: "PRO 테마 강조색",
    subtitle: "버튼과 강조 UI에 사용할 색상을 선택하세요.",
    selected: "선택됨",
  },
};

export const INTER_FONTS = {
  light: "Inter_300Light",
  regular: "Inter_400Regular",
  medium: "Inter_500Medium",
  semiBold: "Inter_600SemiBold",
  bold: "Inter_700Bold",
  extraBold: "Inter_800ExtraBold",
  black: "Inter_900Black",
};
